# Generated by Django 4.2.5 on 2023-09-06 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Original_video_path', models.CharField(blank=True, max_length=50, null=True)),
                ('Converted_video_path', models.CharField(blank=True, max_length=50, null=True)),
                ('Status', models.CharField(max_length=25)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Update_at', models.DateTimeField(auto_now=True)),
                ('User_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Action', models.CharField(max_length=25)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Update_at', models.DateTimeField(auto_now=True)),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='home.video')),
            ],
        ),
    ]
