# Generated by Django 3.2.21 on 2023-09-19 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_site', '0009_merge_20230918_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('original_video_path', models.CharField(blank=True, max_length=50, null=True)),
                ('converted_video_path', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_video', to='auth_site.myuser')),
            ],
        ),
    ]
