# Generated by Django 3.2.21 on 2023-09-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
