# Generated by Django 3.2.6 on 2023-09-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='action',
            new_name='Action',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='created_at',
            new_name='Created_at',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='update_at',
            new_name='Update_at',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='user_id',
            new_name='User_Id',
        ),
        migrations.RemoveField(
            model_name='history',
            name='converted_video_path',
        ),
    ]
