# Generated by Django 3.2.6 on 2023-09-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.BooleanField(default=True),
        ),
    ]
