# Generated by Django 3.2.6 on 2023-09-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(default='user', max_length=10),
        ),
    ]
