# Generated by Django 3.2.6 on 2023-09-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_site', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
