# Generated by Django 3.2.6 on 2023-09-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_site', '0002_auto_20230914_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
