# Generated by Django 3.2.6 on 2023-09-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_site', '0003_alter_myuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(default='admin', max_length=10),
        ),
    ]
