# Generated by Django 4.1.3 on 2023-09-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_site', '0003_rename_user_myuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='User',
        ),
    ]
