# Generated by Django 3.2.6 on 2023-09-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_site', '0004_alter_myuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(default='user', max_length=10),
        ),
    ]
