# Generated by Django 3.2.6 on 2023-09-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_site', '0006_alter_myuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='status',
            field=models.CharField(default='banned', max_length=25),
        ),
    ]
