# Generated by Django 3.2.21 on 2023-09-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_site', '0006_generate_users_data'),
        ('auth_site', '0008_alter_myuser_status'),
    ]

    operations = [
    ]
